### ISSUE TITLE
Doesn't compile on Windows.

### ISSUE THREAD

**Issue by the-goodies** [hasenj/go-vbolt#1]
Doesn't compile on Windows: `undefined: sysMmapFlags` - need to add `flags_windows.go`. Also would be great if you could pass `Options` to `Open`, because now an initial db file size is 1GB: `options.InitialMmapSize = 1024 * 1024 * 1024`.

**Comment by hasenj** [comment]
Thanks for the report.

> would be great if you could pass `Options` to `Open`

The `Open` function provided is more or less just for convenience. You can just call the Open method directly from boltdb. The object we return is the same thing that bolt returns.

**Comment by hasenj** [comment]
Removed the os dependent sysMmapFlags so hopefully this issue is fixed. I'll close this for now. If other problems persist feel free to open another one.
